### ISSUE TITLE
请问这个可以生成画布图片链接吗

### ISSUE THREAD

**Issue by Biytes** [CarlXu94/taro-canvas-helper#1]
请问这个可以生成画布图片链接吗，这个只是单纯的把样式画出来吧

**Comment by BryceXu94** [comment]
> 请问这个可以生成画布图片链接吗，这个只是单纯的把样式画出来吧

可通过微信wx.canvasToTempFilePath导出本地地址

**Comment by Biytes** [comment]
ok了，我刚试了一下，可以，感谢回答
